### ISSUE TITLE
Get more language support info from `github/linguist` on build instead of runtime with only `Java Properties` support

### ISSUE THREAD

**Issue by JounQin** [eemeli/prettier-plugin-properties#5]
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

I'm using this approach for `prettier-plugin-sh` at https://github.com/un-ts/prettier/blob/master/scripts/languages.ts

If you agree, I'd like to raise a PR for it.

**Comment by eemeli** [comment]
I have two initial questions on this:
1. I've not looked, but does this really provide notable filesize savings for a user?
2. Why the `fetch()` for the latest on github.com, rather than grabbing the same from an npm dev dependency?

**Comment by JounQin** [comment]
1. You don't need the whole `linguist-languages` package and the user doesn't neither.
2. `github/linguist` is the official source, `linguist-languages` is packaged by 3rd party and not always latest synced.

**Comment by eemeli** [comment]
Ok, I'll buy the size argument, but I'd still prefer relying on `linguist-languages` to convert the data format and provide it as JSON data; the Java Properties stuff hasn't really changed at all since it was first submitted years ago.

So, happy to consider a PR that moves `linguist-languages` to devDependencies + copies the relevant data file during the build to be vendored into this package. This'll require including a notice on third-party licenses, e.g. copying and extending [this one](https://github.com/ikatyang/linguist-languages/blob/master/ThirdPartyNoticeText.txt).

**Comment by JounQin** [comment]
OK, I'll raise a PR for it.
